<div class="wrap">
	<h2><?php _e('Simple SNAP - Settings', 'simplesnap'); ?></h2>
	
	<p><?php _e('To check for new versions or get more information, visit <a href="http://www.nateomedia.com/wares/downloads/wordpress/simplesnap/">this plugin\'s page</a>.', 'simplesnap'); ?></p>

	<form method="post" action="">
		<?php wp_nonce_field('simple_snap_update_options'); ?>
		
		<input type="hidden" name="info_update" id="info_update" value="true" />
		
		<h3><?php _e('Navigational Menu Options', 'simplesnap'); ?></h3>
		<p><?php _e('<strong>Menu Style</strong> controls how the user will navigate post titles. Three styles are provided to choose from. Numbers will only appear in the menu if post titles beginning with numbers exist and <strong>Group Posts</strong> is turned off. <strong>Recent Posts</strong> controls how many recent posts will be displayed when the plugin is first called (if the recent posts feature is called).', 'simplesnap'); ?></p>
		<p><?php _e('<strong>CSS Class Name</strong> fields add a class attribute to <code>&lt;ol></code> and/or <code>&lt;li></code> HTML tags.', 'simplesnap'); ?></p>
		<p><?php _e('<strong>Ignore During Alphabetizing</strong> allows the user to filter out words, letters and characters such as <em>the</em>, <em>a</em>, or quotation marks from the alphabetization process. This function is not case sensitive. For instance, if "the" is added to the ignore list, the post title "The Last Samurai" would be found under <em>L</em> instead of <em>T</em>. Multiple items can be filtered, but must contain no literal spaces between entries and be seperated with a pipe. To ignore a quotation mark or apostrophe, you must use the following: <code>&quote;</code> or <code>&apost;</code>. For example: <strong><code>the|a|an|&quote;|&apost;</code></strong>', 'simplesnap'); ?></p>
		
		<table class="form-table">
			<tr valign="top">
				<th scope="row"><?php _e('Menu Style', 'simplesnap'); ?></th>
				<td>
					<label style="letter-spacing: 1px;"><input name="key_snap_menu" type="radio" value="1" <?php checked('1', get_option('key_snap_menu')); ?> /> <?php _e('#0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ', 'simplesnap'); ?></label><br />
					<label style="letter-spacing: 1px;"><input name="key_snap_menu" type="radio" value="2" <?php checked('2', get_option('key_snap_menu')); ?> /> <?php _e('# 0-9 A-D E-H I-L M-P Q-T U-Z', 'simplesnap'); ?></label><br />
					<label style="letter-spacing: 1px;"><input name="key_snap_menu" type="radio" value="3" <?php checked('3', get_option('key_snap_menu')); ?> /> <?php _e('# 0-9 A-M N-Z', 'simplesnap'); ?></label>
				</td>
			</tr>
			<tr valign="top">
				<th scope="row"><?php _e('Group Posts', 'simplesnap'); ?></th>
				<td>
					<label><input name="key_snap_menumisc" type="radio" value="1" <?php checked('1', get_option('key_snap_menumisc')); ?> /> <?php _e('Group Post Titles Beginning With a Number', 'simplesnap'); ?></label><br />
					<label><input name="key_snap_menumisc" type="radio" value="2" <?php checked('2', get_option('key_snap_menumisc')); ?> /> <?php _e('Do Not Group Post Titles Beginning With a Number', 'simplesnap'); ?></label><br />
				</td>
			</tr>
			<tr valign="top">
				<th scope="row"><?php _e('Recent Posts', 'simplesnap'); ?></th>
				<td>Display <input name="key_snap_recent" type="text" value="<?php echo get_option('key_snap_recent') ?>" size="20" style="width: 3em;" /> <?php _e('Recent Posts', 'simplesnap'); ?></td>
			</tr>
			<tr valign="top">
				<th scope="row"><code>&lt;ol></code> <?php _e('CSS Class Name', 'simplesnap'); ?></th>
				<td><input name="key_snap_csscls1" type="text" value="<?php echo get_option('key_snap_csscls1') ?>" size="20" style="width: 30em;" /></td>
			</tr>
			<tr valign="top">
				<th scope="row"><code>&lt;li></code> <?php _e('Selected CSS Class Name', 'simplesnap'); ?></th>
				<td><input name="key_snap_csscls2" type="text" value="<?php echo get_option('key_snap_csscls2') ?>" size="20" style="width: 30em;" /></td>
			</tr>
			<tr valign="top">
				<th scope="row"><?php _e('Ignore When Alphabetizing', 'simplesnap'); ?></th> 
				<td><input name="key_snap_exclude" type="text" value="<?php echo get_option('key_snap_exclude') ?>" size="20" style="width: 30em;" /> (<?php _e('optional', 'simplesnap'); ?>)</td>
			</tr>
		</table>
		
		<h3><?php _e('Presentational Options', 'simplesnap'); ?></h3>
		<p><?php _e('<strong>Fancy URLs</strong> should be activated if the Wordpress installation is using a custom URI permalink structure. The <strong>Fancy URL Name</strong> used in the URI may also be&nbsp;customized.', 'simplesnap'); ?></p>
		<p><?php _e('The <strong>Tabs</strong> option is purely for aesthetic purposes &mdash; it allows you to specify how far to indent the ordered list generated by WP-SNAP! so that it matches up with the rest of your HTML&nbsp;code.', 'simplesnap'); ?></p>
		
		<table class="form-table">
			<tr valign="top">
				<th scope="row"><?php _e('Fancy URL Name', 'simplesnap'); ?></th> 
				<td><input name="key_snap_fancyurlname" type="text" value="<?php echo get_option('key_snap_fancyurlname') ?>" size="20" style="width: 30em;" /></td>
			</tr>
			<tr valign="top">
				<th scope="row"><?php _e('Tabs', 'simplesnap'); ?></th> 
				<td><?php _e('Use', 'simplesnap'); ?> <input name="key_snap_tab1" type="text" value="<?php echo get_option('key_snap_tab1') ?>" size="1" style="width: 1.5em;" /> <?php _e('tabs', 'simplesnap'); ?></td>
			</tr>
		</table>
		
		<p class="submit">
			<input type="submit" class="button-primary" name="Submit" value="<?php _e('Save Changes', 'simplesnap'); ?>" />
	</form>
</div>